### PR TITLE
Doc Patch

### PR DESCRIPTION
**Pull request by robelgeda**
Patch for #6 
- Quick patch, I forgot to update the path in the front page README, its currently pointing to where the LaTex folder was.

### CODE REVIEW

**Review by mtrebitsch — APPROVED** [review]
Looks good to me (both files exist)!

**Review by rteyssier — APPROVED** [review]

**Comment by blaizot** [comment]
Hey ! 
This all looks great. Congrats !! 
Just two minor points: 
- should we not name the "wiki" directory "for-users" (or user_doc, or anything explicit like this) ?
- the file docs.md in doc/dev_docs could be renamed README.md and placed in doc/. directly so that it is displayed on the web interface when we open the doc directory. That would be very neat. (That would also leave the directory dev_docs free for a future documentation for developers?).

**Comment by robelgeda** [comment]
@blaizot Thank you! 
I like the idea of having a README and will add it in the next patch. I think renaming "wiki" will require some carful refactoring since things link there (it might not be as bad, but I not sure).

**Comment by cphyc** [comment]
@meeseeksdev backport to dev

**Comment by cphyc** [comment]
@meeseeksdev backport to dev

**Pull request merged**
