### PR TITLE
Add doc build to tests

### PR DESCRIPTION
**Pull request by robelgeda**
This PR adds test to check if the docs build correctly

## PR Checklist

- [x] Pull request points to the `dev` branch.
- [ ] If it is a bugfix, the PR should have label `on-merge: backport-to-stable`.
- [ ] For new code features, the PR should have been tested (please include the results of the tests below or, when possible, add a new test for the feature).

### CODE REVIEW

**Comment by robelgeda** [comment]
Ok, if tests pass here we can merge this before new docs are added and it will test them in the pr

**Review by cphyc — APPROVED** [review]

**Review by cphyc — APPROVED** [review]
Actually, it'd be great to include the doc as a build artifact so we can check them?

**Comment by robelgeda** [comment]
I have added this feature, now it uploads the built docs after the test finishes (both the pdf and html). They can be downloaded as a zipped file! I will update the ticket with instructions.

**Comment by nbrucy** [comment]
Thanks! That is great!

**Pull request merged**
