### PR TITLE
[bugfix] Update rt_init_flow_fine.f90

### PR DESCRIPTION
**Pull request by rteyssier**
This is a (nasty) bug fix for rt simulations with cosmo zooms.

## PR Checklist

- [x ] Pull request points to the `dev` branch.
- [x ] If it is a bugfix, the PR should have label `on-merge: backport-to-stable`.
- [ ] For new code features, the PR should have been tested (please include the results of the tests below or, when possible, add a new test for the feature).

### CODE REVIEW

**Comment by nbrucy** [comment]
What was the problem when `ncache = 0`?

**Comment by rteyssier** [comment]
Segfault...RomainOn Nov 3, 2024, at 1:39 PM, nbrucy ***@***.***> wrote:﻿
What was the problem when ncache = 0?

**Comment by cphyc** [comment]
@nbrucy the `init_array` is only allocated if `ncache>0`, so one can only access it in this case :)

**Review by cphyc — APPROVED** [review]

**Comment by nbrucy** [comment]
@meeseeksdev backport to dev

**Comment by nbrucy** [comment]
@meeseeksdev backport to stable

**Comment by rteyssier** [comment]
What went wrong with the back port ?
Why did we need to do a second pull request for the rt_init_flow_fine big fix ?

Romain

**Pull request merged**
