### PR TITLE
Run automatically test suite

### PR DESCRIPTION
**Pull request by cphyc**
This ports back the automatic test suite to run on any PR open and merge.

On a side note, the tests take about ~30min to run on two cores, and the repo has 2,000 free minutes / month (see https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes), so we're good to run them approximately ~60× per month.

### CODE REVIEW

**Comment by cphyc** [comment]
@rteyssier I've included the test that was running daily as a requirement for the acceptance of any future PR.

Regarding the failing test, it looks like the `barotrop` test fails on 6060289 with an error of 3.4e-12. Should we update the results?

The PDF and the log can be accessed as follows (for this PR and all future ones).
image
image
image

**Comment by rteyssier** [comment]
Do we store the pdf and the log? This was a problem on the bitbucket repo and causing the wiki repo to inflate rapidly.

**Comment by rteyssier** [comment]
Yes I think we can update the reference data for the barotrop test.
Ideally, we want to use the data generated on the GitHub architecture using 2 cores.

**Comment by cphyc** [comment]
Both are getting destroyed after 90 days by default, so it should be fine. Unlike bitbucket, we can remove those (called artifacts on GitHub). However, this means we do not keep the logs for tests older than 90days!

**Comment by cphyc** [comment]
> Yes I think we can update the reference data for the barotrop test. Ideally, we want to use the data generated on the GitHub architecture using 2 cores.

OK, I'm not sure I'll have time to update the answers in the coming weeks, so would you be happy if I just adapted the barotrop one and defer the point above to the future?

**Comment by rteyssier** [comment]
> > Yes I think we can update the reference data for the barotrop test. Ideally, we want to use the data generated on the GitHub architecture using 2 cores.
> 
> OK, I'm not sure I'll have time to update the answers in the coming weeks, so would you be happy if I just adapted the barotrop one and defer the point above to the future?

Yes of course. Go ahead and let me know when I can merge.

**Comment by cphyc** [comment]
Assuming the tests pass, this should be good to go.

**Review by rteyssier — APPROVED** [review]

**Pull request merged**
