### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by rteyssier**
## PR Checklist

- [ ] Pull request points to the `dev` branch.
- [ ] If it is a bugfix, the PR should have label `on-merge: backport-to-stable`.
- [ ] For new code features, the PR should have been tested (please include the results of the tests below or, when possible, add a new test for the feature).

### CODE REVIEW

**Comment by cphyc** [comment]
What is this PR doing @rteyssier?

**Comment by rteyssier** [comment]
This is a bug fix for the AGN feedback routine.

**Comment by nbrucy** [comment]
This would merge all dev into stable. I'll close this and merge only the bugfix.

**Comment by nbrucy** [comment]
Replaced by PR #35

**Pull request closed without merging**
